/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene el estado del backend */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backend disponible */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista insumos activos */
        get: {
            parameters: {
                query?: {
                    /** @description Filtro por nombre */
                    q?: string;
                    /** @description Cantidad maxima de resultados */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de insumos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ingredient"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Crea un insumo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIngredientInput"];
                };
            };
            responses: {
                /** @description Insumo creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngredientMutationResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene un insumo por id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId de MongoDB */
                    id: components["parameters"]["ObjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Insumo encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ingredient"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Actualiza un insumo */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId de MongoDB */
                    id: components["parameters"]["ObjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIngredientInput"];
                };
            };
            responses: {
                /** @description Insumo actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngredientMutationResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /** Desactiva un insumo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ObjectId de MongoDB */
                    id: components["parameters"]["ObjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Insumo desactivado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista compras registradas */
        get: {
            parameters: {
                query?: {
                    /** @description Filtra compras por insumo */
                    ingredientId?: string;
                    /** @description Cantidad maxima de resultados */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de compras */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseRecord"][];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Registra una compra y recalcula WAC */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePurchaseRecordInput"];
                };
            };
            responses: {
                /** @description Compra registrada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PurchaseRecordMutationResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponse: {
            /** @example ok */
            status: string;
            /** @example Backend is running and connected to MongoDB */
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
        MessageResponse: {
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
        Ingredient: {
            /** @example 665100000000000000000001 */
            _id: string;
            /** @example Leche entera */
            name: string;
            /** @example litro */
            unit: string;
            /** @example 120 */
            currentStock: number;
            /** @example 11.58 */
            averageCost: number;
            /** @example 20 */
            minimumStock: number;
            /** @example true */
            active: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateIngredientInput: {
            /** @example Leche entera */
            name: string;
            /** @example litro */
            unit: string;
            /** @default 0 */
            currentStock: number;
            /** @default 0 */
            averageCost: number;
            /** @default 0 */
            minimumStock: number;
        };
        IngredientMutationResponse: {
            message: string;
            ingredient: components["schemas"]["Ingredient"];
            /** Format: date-time */
            timestamp: string;
        };
        PurchaseRecord: {
            /** @example 665200000000000000000001 */
            _id: string;
            /** @example Lacteos del Valle */
            provider: string;
            /** Format: date-time */
            invoiceDate: string;
            ingredient: components["schemas"]["Ingredient"];
            /** @example 20 */
            quantityReceived: number;
            /** @example 240 */
            totalPrice: number;
            /** @example 12 */
            unitPrice: number;
            /** @example 100 */
            previousStock: number;
            /** @example 11.5 */
            previousAverageCost: number;
            /** @example 120 */
            newStock: number;
            /** @example 11.58 */
            newAverageCost: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreatePurchaseRecordInput: {
            /** @example Lacteos del Valle */
            provider: string;
            /**
             * Format: date
             * @example 2026-05-25
             */
            invoiceDate: string;
            /** @example 665100000000000000000001 */
            ingredientId: string;
            /** @example 20 */
            quantityReceived: number;
            /** @example 240 */
            totalPrice: number;
        };
        PurchaseRecordMutationResponse: {
            message: string;
            purchaseRecord: components["schemas"]["PurchaseRecord"];
            ingredient: components["schemas"]["Ingredient"];
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: {
        /** @description Solicitud invalida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MessageResponse"];
            };
        };
        /** @description Recurso no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MessageResponse"];
            };
        };
        /** @description Error interno del servidor */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MessageResponse"];
            };
        };
    };
    parameters: {
        /** @description ObjectId de MongoDB */
        ObjectId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
